import type { Metadata } from "next";
import { Figtree, Nunito, Urbanist } from "next/font/google";
import "./globals.css";

export const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
  display: "swap",
  weight: ["400", "500", "600", "700", "800"], // SemiBold and ExtraBold
});

export const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  display: "swap",
  weight: ["400", "500", "600", "700", "800"], // SemiBold and ExtraBold
});

export const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist",
  display: "swap",
  weight: ["400", "500", "600", "700", "800"], // SemiBold and ExtraBold
});

export const metadata: Metadata = {
  title: "Fametonic App",
  description: "Generated by Fametonic app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable} ${urbanist.variable} ${nunito.variable}  `}
      >
        {children}
      </body>
    </html>
  );
}
