import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";

export const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
  display: "swap",
  weight: ["600", "800"], // SemiBold and ExtraBold
});

export const metadata: Metadata = {
  title: "Fametonic App",
  description: "Generated by Fametonic app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.variable} antialiased`}>{children}</body>
    </html>
  );
}
